---
- name: Inventory Assertion
  hosts: localhost
  gather_facts: false
  roles:
  - inventory_validation

- name: Getting fects
  hosts: all
  user: "{{ USER }}"
  become: yes
  gather_facts: true

- name: Generating Stack Passwords
  hosts: localhost
  tasks:
  - add_host:
      name: PASSWORD_HOLDER
      KEEP_AVALIVE_PASSWORD_AUTH: "{{ lookup('password', '/dev/null length=5') }}"
      HAPROXY_WEB_CONSOLE_PASSWORD: "{{ lookup('password', '/dev/null length=16') }}"

- name: Generated Stack Password
  hosts: localhost
  roles:
  - generated_passwords

- hosts: HAPROXY_PRIMARY, HAPROXY_SECONDARY
  become: yes
  user: "{{ USER }}"
  roles:
  - haproxy

- hosts: KUBERNETES_MASTER_INIT, KUBERNETES_MASTERS, KUBERNETES_NODES
  become: yes
  user: "{{ USER }}"
  roles:
  - install_kubernetes

- hosts: KUBERNETES_MASTER_INIT
  become: yes
  user: "{{ USER }}"
  roles:
  - create_cluster

- hosts: KUBERNETES_MASTERS
  become: yes
  user: "{{ USER }}"
  roles:
  - { role: join_masters, when: MULTIMASTER_MODE | bool }

- hosts: KUBERNETES_NODES
  become: yes
  user: "{{ USER }}"
  roles:
  - join_nodes

- hosts: KUBERNETES_MASTER_INIT
  become: yes
  user: "{{ USER }}"
  roles:
  - { role: csr_approve, when: TLS_ENABLED | bool }
