all:
  vars:
    #-> General
    USER: vagrant
    # ansible_ssh_private_key_file: /home/danilo/.ssh/danilo.souza_mandic.pem
    FIREWALL: 'False'

    #-> HaProxy
    HAPROXY_ENABLED: 'True'

    CLUSTER_HAPROXY: 'False'
    SINGLE_HAPROXY: 'True'
    VRRP_IP_ADDRESS: 192.168.15.37

    WEB_ADMINISTRATION_HAPROXY_ENABLED: 'False'
    HAPROXY_WEB_USER: ''

    #-> Kubernetes
    KUBERNETES_MULTIMASTER_MODE: 'True'
    KUBERNTES_SINGLE_MODE: 'False'
    KUBERNETES_SECURITY_PORT: '6443'

    METALLB_ENABLED: 'True'
    METALLB_RANGEIP_BEGIN: 192.168.15.38
    METALLB_RANGEIP_END: 192.168.15.39

    TLS_ENABLED: 'True'

    #-> Container Runtime
    CRIO: 'True'
    CONTAINERD: 'False'

  #-> Inventory
  children:

    k8s:
      children:
        KUBERNETES_MASTER_INIT:
          hosts:
            192.168.15.32

        KUBERNETES_MASTERS:
          hosts:
            192.168.15.33:
            192.168.15.34:

        KUBERNETES_NODES:
          hosts:
            192.168.15.35:

    haproxy:
      children:
        HAPROXY_PRIMARY:
          hosts:
            192.168.15.30

        HAPROXY_SECONDARY:
          hosts:
            
