all:
  vars:
    #-> General Section
    USER: vagrant
    # ansible_ssh_private_key_file: /home/danilo/.ssh/danilo.souza_mandic.pem
    FIREWALL: 'False'

    #-> HaProxy Section
    HAPROXY_ENABLED: 'False'

    CLUSTER_HAPROXY: 'False'
    SINGLE_HAPROXY: 'False'
    VRRP_IP_ADDRESS: 172.16.1.37

    WEB_ADMINISTRATION_HAPROXY_ENABLED: 'False'
    HAPROXY_WEB_USER: ''

    #-> Kubernetes Section
    KUBERNETES_MULTIMASTER_MODE: 'False'
    KUBERNTES_SINGLE_MODE: 'True'
    KUBERNETES_SECURITY_PORT: 6443

    METALLB_ENABLED: 'True'
    METALLB_RANGEIP_BEGIN: 172.16.1.38
    METALLB_RANGEIP_END: 172.16.1.40

    TLS_ENABLED: 'True'

    #-> Container Runtime
    CRIO: 'True'

  #-> Inventory
  children:

    k8s:
      children:
        KUBERNETES_MASTER_INIT:
          hosts:
            172.16.1.32

        KUBERNETES_MASTERS:
          hosts:

        KUBERNETES_NODES:
          hosts:
            172.16.1.35:

    haproxy:
      children:
        HAPROXY_PRIMARY:
          hosts:

        HAPROXY_SECONDARY:
          hosts: