all:
  vars:
    USER: vagrant
    # ansible_ssh_private_key_file:

    ##- General Section
    FIREWALL: 'True'

    ##- HaProxy Section
    HA_HAPROXY: 'True'
    SINGLE_HAPROXY: 'False'

    HAPROXY_WEB_USER: haproxy

    ##- Kubernetes Section
    MULTIMASTER_MODE: 'True'
    SINGLE_MODE: 'False'

    TLS_ENABLED: 'True'
    KUBERNETES_VERSION: 1.18.8
    SECURITY_PORT: 6443
    LOADBALANCER: 192.168.15.36
    METALLB_RANGEIP_BEGIN: 192.168.15.37
    METALLB_RANGEIP_END: 192.168.15.40

  ##- Inventory
  children:

    k8s:
      children:
        KUBERNETES_MASTER_INIT:
          hosts:
            192.168.15.32

        KUBERNETES_MASTERS:
          hosts:
            192.168.15.33:

        KUBERNETES_NODES:
          hosts:
            192.168.15.34:
            192.168.15.35:

    haproxy:
      children:
        HAPROXY_PRIMARY:
          hosts:
            192.168.15.30
        HAPROXY_SECONDARY:
          hosts:
            192.168.15.31
