default_kubernetes_cni_weavenet_manifestUrl: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
# weave net sem NAT na rede.
kubernetes_cni_weavenet_manifestUrl_without_nat: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.NO_MASQ_LOCAL=1"

kubernetes_cni_cilium_manifestUrl: "https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml"

metallb_kubernetes_namespace_manifestUrl: "https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml"

metallb_kubernetes_deploy_manifestUrl: "https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml"

metric_server_kubernetes_deploy_manifestUrl: "https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.3/components.yaml"