---
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
  listen: "restart keepalived"

- name: enable keepalived
  systemd:
    name: keepalived
    enabled: yes
  listen: "enable keepalived"

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
  listen: "restart haproxy"

- name: enable haproxy
  systemd:
    name: haproxy
    enabled: yes
  listen: "enable haproxy"
